spring.profiles.active=${SPRING_PROFILES_ACTIVE:test}

jwt.secret=${JWT_SECRET:chaveLocalApenasParaDesenvolvimento64caracteresNoMinimo123456}
jwt.expiration=${JWT_EXPIRATION:604800000}
spring.threads.virtual.enabled=true
logging.level.com.ygor.helpdesk=DEBUG
server.port=${PORT:8080}

